python enjoy.py \
    --env-name InmoovHandPlaceBulletEnv-v9 \
    --load-dir trained_models_0404_0_n_place_0404_0/ppo \
    --non-det 0 \
    --seed=18980 \
    --random_top_shape 1 \
    --renders 0 \
    --exclude_hard 0 \
    --obs_noise 1 \
    --n_best_cand 2 \
    --cotrain_stack_place 1 \
    --grasp_pi_name "0404_0_n_20_40" \
    --save_states 1 \
    --states_dir "/home/michelle/mguo/data/states/partial/placing_v002" \
    --n_trials 100
